- hosts: localhost
  connection: local
  gather_facts: false
  collections:
  - netbox.netbox
  - cisco.nso

  pre_tasks:
    - name: Load NSO Variable Files
      include_vars:
        file: host_vars/nso-api.yml
        name: nso
    - name: Load Netbox Variable Files
      include_vars:
        file: host_vars/netbox-api.yml
        name: netbox
    - name: Load PON Networks
      include_vars:
        file: group_vars/pon_networks.yml
        name: pon

  tasks:
    # - include_tasks: "tasks/olt_deploy.yml"
    #   loop: "{{ pon.sites }}"
    #   loop_control:
    #     loop_var: site
    - name: "STEP1: All Active Anycast EVPN IRB"
      nso_config:
        url: "{{ nso.url }}"
        username: "{{ nso.username }}"
        password: "{{ nso.password }}"
        data:
          evpn_irb:evpn_irb:
          - name: EPH
            device:
            - EVPN-PE0-RTR
            - EVPN-PE1-RTR
            - EVPN-PE2-RTR
            - EVPN-PE3-RTR
            vrfs:
              vrf:
              - vrf_name: EPH_INTERNET
                description: INTERNET
                my_bgp_as: 65000
                my_vrf_community: 201
                v4_imports:
                - vrf_community: 1
                  bgp_as: 65000
              - vrf_name: EPH_VIDEO
                description: VIDEO
                my_bgp_as: 65000
                my_vrf_community: 203
                v4_imports:
                - vrf_community: 3
                  bgp_as: 65000
              - vrf_name: EPH_VOICE
                description: VOICE
                my_bgp_as: 65000
                my_vrf_community: 202
                v4_imports:
                - vrf_community: 2
                  bgp_as: 65000
            bgp:
              bgp_as: 65000
              vrf:
              - vrf_name: EPH_INTERNET
              - vrf_name: EPH_VOICE
              - vrf_name: EPH_VIDEO
            interfaces:
              interface:
              - interface_type: BVI
                interface_number: '201'
                description: EPH_INT
                ipv4_address: 172.16.201.1
                ipv4_mask: 255.255.255.0
                vrf: EPH_INTERNET
                mac_address: 0000.0201.0000
              - interface_type: BVI
                interface_number: '202'
                description: VOICE
                ipv4_address: 172.16.202.1
                ipv4_mask: 255.255.255.0
                vrf: EPH_VOICE
                mac_address: 0000.0202.0000
              - interface_type: BVI
                interface_number: '203'
                description: VIDEO
                ipv4_address: 172.16.203.1
                ipv4_mask: 255.255.255.0
                vrf: EPH_VIDEO
                mac_address: 0000.0203.0000
            evpn:
              evi:
              - evi_id: 201
              - evi_id: 202
              - evi_id: 203
            l2vpn:
              group_name: EPH_OLTS
              bridge_domain:
              - bd_name: INTERNET
                interface:
                - interface_type: BVI
                  interface_number: '201'
                evi_id: 201
              - bd_name: VOICE
                interface:
                - interface_type: BVI
                  interface_number: '202'
                evi_id: 202





