- hosts: localhost
  connection: local
  gather_facts: false
  collections:
  - netbox.netbox
  - cisco.nso

  pre_tasks:
    - name: Load NSO Variable Files
      include_vars:
        file: host_vars/nso-api.yml
        name: nso
    - name: Load Netbox Variable Files
      include_vars:
        file: host_vars/netbox-api.yml
        name: netbox
    - name: Load PON Networks
      include_vars:
        file: group_vars/pon_networks.yml
        name: pon

  tasks:

  - name: Render NSO Play
    template:
      src: templates/deploy_olt.j2
      dest: output/deploy_olt.yml

  - include_tasks: output/deploy_olt.yml

