---

# Site Dictionary available here - has all information in a single variable per site called 'site'

- name: "###### {{ site.name }} ###### STEP1: All Active Anycast EVPN IRB"
  nso_config:
    url: "{{ nso.url }}"
    username: "{{ nso.username }}"
    password: "{{ nso.password }}"
    data:
      evpn_irb:evpn_irb:
      - name: "{{ site.plug }}"
        device: "{{ site.devices }}"
        vrfs:
          vrf:
          - vrf_name: "{{ site.plug }}_{{ vrf.name }}"
            description: "{{ vrf.name }}"
            my_bgp_as: "{{ pon.bgp_as }}"
            my_vrf_community: "{{ vrf.community }}"
            v4_imports:
            - vrf_community: 1
              bgp_as: "{{ pon.bgp_as }}"
        bgp:
          bgp_as: "{{ pon.bgp_as }}"
          vrf:
          - vrf_name: "{{ site.plug }}_{{ vrf.name }}"
        interfaces:
          interface:
          - interface_type: BVI
            interface_number: "{{ vrf.community }}"
            description: "{{ site.plug }}_{{ vrf.name }}"
            ipv4_address: "{{ vrf.ipv4_address }}"
            ipv4_mask: "{{ vrf.ipv4_mask }}"
            vrf: "{{ site.plug }}_{{ vrf.name }}"
            mac_address: "badb.b{{ vrf.community }}.0000"
        evpn:
          evi:
          - evi_id: "{{ vrf.community }}"
        l2vpn:
          group_name: "{{ site.plug }}_OLTs"
          bridge_domain:
          - bd_name: "{{ vrf.name }}"
            interface:
            - interface_type: BVI
              interface_number: "{{ vrf.community }}"
            evi_id: "{{ vrf.community }}"

  loop: "{{ site.networks }}"
  loop_control:
    loop_var: vrf

- include_tasks: "tasks/02_olt_deploy.yml"
  loop: "{{ site.olts }}"
  loop_control:
    loop_var: olt

  