---
# Site Dictionary available here - site
# OLT Dictionary available here - olt

- name: "DEBUGGIN"
  debug:
    msg: "{{ interface }}"
  loop: "{{ olt.interfaces }}"
  loop_control:
    loop_var: interface


- name: "STEP2: Deploy OLTs"
  nso_config:
    url: "{{ nso.url }}"
    username: "{{ nso.username }}"
    password: "{{ nso.password }}"
    data:
      olt_deploy:olt_deploy:
      - name: "{{ site.plug }}"
        pe:
        - device: "{{ interface.device }}"
          interfaces:
            interface:
            - interface_type: Bundle-Ether
              interface_number: "{{ olt.id }}"
              description: "{{ site.plug }}_{{ olt.name }}"
              lacp_mode: active
              lacp_mac_address: "badb.ad{{ olt.id }}.0000"
          evpn:
            interface:
            - interface_type: Bundle-Ether
              interface_number: "{{ olt.id }}"
              esi_identifier: "00.6e.65.62.72.65.64.6c.65.{{ olt.id }}"
          l2vpn:
            group_name: "{{ site.plug }}_OLTs"
            bridge_domain:
            - bd_name: INTERNET
              interface:
              - interface_type: Bundle-Ether
                interface_number: '10.201'

  loop: "{{ olt.interfaces }}"
  loop_control:
    loop_var: interface