- name: "########### STEP1: All Active Anycast EVPN IRB"
  nso_config:
    url: "http://172.28.128.3:8080/jsonrpc"
    username: "admin"
    password: "admin"
    data:
      evpn_irb:evpn_irb:
      - name: EPH
        device:
        - EVPN-PE0-RTR
        - EVPN-PE1-RTR
        - EVPN-PE0-RTR
        - EVPN-PE1-RTR
        vrfs:
          vrf:
          - vrf_name: EPH_INTERNET
            description: INTERNET
            my_bgp_as: 65000
            my_vrf_community: 201
            v4_imports:
            - vrf_community: 1
              bgp_as: 65000
          - vrf_name: EPH_VOICE
            description: VOICE
            my_bgp_as: 65000
            my_vrf_community: 202
            v4_imports:
            - vrf_community: 2
              bgp_as: 65000
          - vrf_name: EPH_VIDEO
            description: VIDEO
            my_bgp_as: 65000
            my_vrf_community: 203
            v4_imports:
            - vrf_community: 3
              bgp_as: 65000
        bgp:
          bgp_as: 65000
          vrf:
          - vrf_name: EPH_INTERNET
          - vrf_name: EPH_VOICE
          - vrf_name: EPH_VIDEO
        interfaces:
          interface:
          - interface_type: BVI
            interface_number: 201
            description: EPH_INTERNET
            ipv4_address: 172.16.201.1
            ipv4_mask: 172.16.201.1
            vrf: EPH_INTERNET
            mac_address: badb.a201.0010
          - interface_type: BVI
            interface_number: 202
            description: EPH_VOICE
            ipv4_address: 172.16.202.1
            ipv4_mask: 172.16.202.1
            vrf: EPH_VOICE
            mac_address: badb.a202.0010
          - interface_type: BVI
            interface_number: 203
            description: EPH_VIDEO
            ipv4_address: 172.16.203.1
            ipv4_mask: 172.16.203.1
            vrf: EPH_VIDEO
            mac_address: badb.a203.0010
        evpn:
          evi:
          - evi_id: 201
          - evi_id: 202
          - evi_id: 203
        l2vpn:
          group_name: EPH_OLTS
          bridge_domain:
          - bd_name: INTERNET
            interface:
            - interface_type: BVI
              interface_number: 201
            evi_id: 201
          - bd_name: VOICE
            interface:
            - interface_type: BVI
              interface_number: 202
            evi_id: 202
          - bd_name: VIDEO
            interface:
            - interface_type: BVI
              interface_number: 203
            evi_id: 203
      - name: STB
        device:
        - EVPN-PE2-RTR
        - EVPN-PE3-RTR
        - EVPN-PE2-RTR
        - EVPN-PE3-RTR
        vrfs:
          vrf:
          - vrf_name: STB_INTERNET
            description: INTERNET
            my_bgp_as: 65000
            my_vrf_community: 101
            v4_imports:
            - vrf_community: 1
              bgp_as: 65000
          - vrf_name: STB_VOICE
            description: VOICE
            my_bgp_as: 65000
            my_vrf_community: 102
            v4_imports:
            - vrf_community: 2
              bgp_as: 65000
          - vrf_name: STB_VIDEO
            description: VIDEO
            my_bgp_as: 65000
            my_vrf_community: 103
            v4_imports:
            - vrf_community: 3
              bgp_as: 65000
        bgp:
          bgp_as: 65000
          vrf:
          - vrf_name: STB_INTERNET
          - vrf_name: STB_VOICE
          - vrf_name: STB_VIDEO
        interfaces:
          interface:
          - interface_type: BVI
            interface_number: 101
            description: STB_INTERNET
            ipv4_address: 172.16.101.1
            ipv4_mask: 172.16.101.1
            vrf: STB_INTERNET
            mac_address: badb.a101.0011
          - interface_type: BVI
            interface_number: 102
            description: STB_VOICE
            ipv4_address: 172.16.102.1
            ipv4_mask: 172.16.102.1
            vrf: STB_VOICE
            mac_address: badb.a102.0011
          - interface_type: BVI
            interface_number: 103
            description: STB_VIDEO
            ipv4_address: 172.16.103.1
            ipv4_mask: 172.16.103.1
            vrf: STB_VIDEO
            mac_address: badb.a103.0011
        evpn:
          evi:
          - evi_id: 101
          - evi_id: 102
          - evi_id: 103
        l2vpn:
          group_name: STB_OLTS
          bridge_domain:
          - bd_name: INTERNET
            interface:
            - interface_type: BVI
              interface_number: 101
            evi_id: 101
          - bd_name: VOICE
            interface:
            - interface_type: BVI
              interface_number: 102
            evi_id: 102
          - bd_name: VIDEO
            interface:
            - interface_type: BVI
              interface_number: 103
            evi_id: 103

    
      olt_deploy:olt_deploy:
      - name: EPH
        pe:
        - device: EVPN-PE0-RTR
          interfaces:
            interface:
            - interface_type: Bundle-Ether
              interface_number: 10
              description: EPH_ROLT10
              lacp_mode: active
              lacp_mac_address: badb.ad10.0010
            - interface_type: Bundle-Ether
              interface_number: 10.201
              description: INTERNET
              outer_vlan: 201
            - interface_type: Bundle-Ether
              interface_number: 10.202
              description: VOICE
              outer_vlan: 202
            - interface_type: Bundle-Ether
              interface_number: 10.203
              description: VIDEO
              outer_vlan: 203
            - interface_type: TenGigE
              interface_number: 0/0/0/10
              description: EPH_ROLT10
              bundle_id: 10
              lacp_mode: active
        - device: EVPN-PE1-RTR
          interfaces:
            interface:
            - interface_type: Bundle-Ether
              interface_number: 10
              description: EPH_ROLT10
              lacp_mode: active
              lacp_mac_address: badb.ad10.0010
            - interface_type: Bundle-Ether
              interface_number: 10.201
              description: INTERNET
              outer_vlan: 201
            - interface_type: Bundle-Ether
              interface_number: 10.202
              description: VOICE
              outer_vlan: 202
            - interface_type: Bundle-Ether
              interface_number: 10.203
              description: VIDEO
              outer_vlan: 203
            - interface_type: TenGigE
              interface_number: 0/0/0/10
              description: EPH_ROLT10
              bundle_id: 10
              lacp_mode: active
          evpn:
            interface:
            - interface_type: Bundle-Ether
              interface_number: 10
              esi_identifier: 10.6e.65.62.72.65.64.6c.65.10
          l2vpn:
            group_name: EPH_OLTS
            bridge_domain:
            - bd_name: INTERNET
              interface:
              - interface_type: Bundle-Ether
                interface_number: 10.201
            - bd_name: VOICE
              interface:
              - interface_type: Bundle-Ether
                interface_number: 10.202
            - bd_name: VIDEO
              interface:
              - interface_type: Bundle-Ether
                interface_number: 10.203
      olt_deploy:olt_deploy:
      - name: EPH
        pe:
        - device: EVPN-PE0-RTR
          interfaces:
            interface:
            - interface_type: Bundle-Ether
              interface_number: 11
              description: EPH_ROLT11
              lacp_mode: active
              lacp_mac_address: badb.ad11.0010
            - interface_type: Bundle-Ether
              interface_number: 11.201
              description: INTERNET
              outer_vlan: 201
            - interface_type: Bundle-Ether
              interface_number: 11.202
              description: VOICE
              outer_vlan: 202
            - interface_type: Bundle-Ether
              interface_number: 11.203
              description: VIDEO
              outer_vlan: 203
            - interface_type: TenGigE
              interface_number: 0/0/0/11
              description: EPH_ROLT11
              bundle_id: 11
              lacp_mode: active
        - device: EVPN-PE1-RTR
          interfaces:
            interface:
            - interface_type: Bundle-Ether
              interface_number: 11
              description: EPH_ROLT11
              lacp_mode: active
              lacp_mac_address: badb.ad11.0010
            - interface_type: Bundle-Ether
              interface_number: 11.201
              description: INTERNET
              outer_vlan: 201
            - interface_type: Bundle-Ether
              interface_number: 11.202
              description: VOICE
              outer_vlan: 202
            - interface_type: Bundle-Ether
              interface_number: 11.203
              description: VIDEO
              outer_vlan: 203
            - interface_type: TenGigE
              interface_number: 0/0/0/11
              description: EPH_ROLT11
              bundle_id: 11
              lacp_mode: active
          evpn:
            interface:
            - interface_type: Bundle-Ether
              interface_number: 11
              esi_identifier: 10.6e.65.62.72.65.64.6c.65.11
          l2vpn:
            group_name: EPH_OLTS
            bridge_domain:
            - bd_name: INTERNET
              interface:
              - interface_type: Bundle-Ether
                interface_number: 11.201
            - bd_name: VOICE
              interface:
              - interface_type: Bundle-Ether
                interface_number: 11.202
            - bd_name: VIDEO
              interface:
              - interface_type: Bundle-Ether
                interface_number: 11.203
      olt_deploy:olt_deploy:
      - name: STB
        pe:
        - device: EVPN-PE2-RTR
          interfaces:
            interface:
            - interface_type: Bundle-Ether
              interface_number: 10
              description: STB_ROLT10
              lacp_mode: active
              lacp_mac_address: badb.ad10.0011
            - interface_type: Bundle-Ether
              interface_number: 10.101
              description: INTERNET
              outer_vlan: 101
            - interface_type: Bundle-Ether
              interface_number: 10.102
              description: VOICE
              outer_vlan: 102
            - interface_type: Bundle-Ether
              interface_number: 10.103
              description: VIDEO
              outer_vlan: 103
            - interface_type: TenGigE
              interface_number: 0/0/0/10
              description: STB_ROLT10
              bundle_id: 10
              lacp_mode: active
        - device: EVPN-PE3-RTR
          interfaces:
            interface:
            - interface_type: Bundle-Ether
              interface_number: 10
              description: STB_ROLT10
              lacp_mode: active
              lacp_mac_address: badb.ad10.0011
            - interface_type: Bundle-Ether
              interface_number: 10.101
              description: INTERNET
              outer_vlan: 101
            - interface_type: Bundle-Ether
              interface_number: 10.102
              description: VOICE
              outer_vlan: 102
            - interface_type: Bundle-Ether
              interface_number: 10.103
              description: VIDEO
              outer_vlan: 103
            - interface_type: TenGigE
              interface_number: 0/0/0/10
              description: STB_ROLT10
              bundle_id: 10
              lacp_mode: active
          evpn:
            interface:
            - interface_type: Bundle-Ether
              interface_number: 10
              esi_identifier: 11.6e.65.62.72.65.64.6c.65.10
          l2vpn:
            group_name: STB_OLTS
            bridge_domain:
            - bd_name: INTERNET
              interface:
              - interface_type: Bundle-Ether
                interface_number: 10.101
            - bd_name: VOICE
              interface:
              - interface_type: Bundle-Ether
                interface_number: 10.102
            - bd_name: VIDEO
              interface:
              - interface_type: Bundle-Ether
                interface_number: 10.103
      olt_deploy:olt_deploy:
      - name: STB
        pe:
        - device: EVPN-PE2-RTR
          interfaces:
            interface:
            - interface_type: Bundle-Ether
              interface_number: 11
              description: STB_ROLT11
              lacp_mode: active
              lacp_mac_address: badb.ad11.0011
            - interface_type: Bundle-Ether
              interface_number: 11.101
              description: INTERNET
              outer_vlan: 101
            - interface_type: Bundle-Ether
              interface_number: 11.102
              description: VOICE
              outer_vlan: 102
            - interface_type: Bundle-Ether
              interface_number: 11.103
              description: VIDEO
              outer_vlan: 103
            - interface_type: TenGigE
              interface_number: 0/0/0/11
              description: STB_ROLT11
              bundle_id: 11
              lacp_mode: active
        - device: EVPN-PE3-RTR
          interfaces:
            interface:
            - interface_type: Bundle-Ether
              interface_number: 11
              description: STB_ROLT11
              lacp_mode: active
              lacp_mac_address: badb.ad11.0011
            - interface_type: Bundle-Ether
              interface_number: 11.101
              description: INTERNET
              outer_vlan: 101
            - interface_type: Bundle-Ether
              interface_number: 11.102
              description: VOICE
              outer_vlan: 102
            - interface_type: Bundle-Ether
              interface_number: 11.103
              description: VIDEO
              outer_vlan: 103
            - interface_type: TenGigE
              interface_number: 0/0/0/11
              description: STB_ROLT11
              bundle_id: 11
              lacp_mode: active
          evpn:
            interface:
            - interface_type: Bundle-Ether
              interface_number: 11
              esi_identifier: 11.6e.65.62.72.65.64.6c.65.11
          l2vpn:
            group_name: STB_OLTS
            bridge_domain:
            - bd_name: INTERNET
              interface:
              - interface_type: Bundle-Ether
                interface_number: 11.101
            - bd_name: VOICE
              interface:
              - interface_type: Bundle-Ether
                interface_number: 11.102
            - bd_name: VIDEO
              interface:
              - interface_type: Bundle-Ether
                interface_number: 11.103
