---

# Site Dictionary available here - has all information in a single variable per site called 'site'

- name: "###### {{ site.name }} ###### STEP1: Deploy PON VRFs"
  nso_config:
    url: "{{ nso.url }}"
    username: "{{ nso.username }}"
    password: "{{ nso.password }}"
    data:
      vrf:vrf:
      - name: "{{ site.plug }}_{{ vrf.name }}"
        vrf_name: "{{ site.plug }}_{{ vrf.name }}"
        description: "NSO_{{ site.plug }}_{{ vrf.name }}"
        my_bgp_as: "{{ pon.bgp_as }}"
        my_vrf_community: "{{ vrf.community }}" 
        v4_imports:
          - vrf_community: 2
            bgp_as: 65000
        device:
          "{{ site.devices }}"
  loop: "{{ site.networks }}"
  loop_control:
    loop_var: vrf
  
- include_tasks: "deploy_bvi.yml"
  loop: "{{ site.devices }}"
  loop_control:
    loop_var: device

- include_tasks: "deploy_olt.yml"
  loop: "{{ site.olts }}"
  loop_control:
    loop_var: olt

